# Generated by Django 5.0.12 on 2025-06-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labnotebook',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
