# Generated by Django 5.0.12 on 2025-07-01 20:11

import django.db.models.deletion
import labs.utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_alter_labnotebook_description_alter_labnotebook_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebookmetric',
            options={'ordering': ['notebook', 'version_obj__version', 'position']},
        ),
        migrations.CreateModel(
            name='NotebookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('html_file', models.FileField(upload_to=labs.utils.utils.upload_to_lab_notebook, validators=[labs.utils.utils.validate_html_file_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='labs.labnotebook')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('notebook', 'version')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='notebookmetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notebookmetric',
            name='version_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='labs.notebookversion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='notebookmetric',
            unique_together={('version_obj', 'position')},
        ),
        migrations.RemoveField(
            model_name='notebookmetric',
            name='version',
        ),
    ]
