# Generated by Django 5.0.12 on 2025-07-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_alter_notebookmetric_options_notebookversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookmetric',
            name='is_preview',
            field=models.BooleanField(default=True),
        ),
    ]
