# Generated by Django 5.0.12 on 2025-07-08 15:28

import labs.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_alter_notebookmetric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labnotebook',
            name='file',
            field=models.FileField(max_length=250, upload_to=labs.utils.utils.upload_to_lab_notebook, validators=[labs.utils.utils.validate_html_file_extension]),
        ),
        migrations.AlterField(
            model_name='notebookmetric',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=labs.utils.utils.upload_to_metric_labs),
        ),
    ]
