# Generated by Django 5.0.12 on 2025-07-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_type'),
        ('labs', '0008_alter_labnotebook_file_alter_notebookmetric_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labnotebook',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_notebooks', to='accounts.organization'),
        ),
    ]
