# Generated by Django 5.0.12 on 2025-07-14 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_type'),
        ('labs', '0009_alter_labnotebook_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='labnotebook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_notebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labnotebook',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_notebooks', to='accounts.organization'),
            preserve_default=False,
        ),
    ]
