# Generated by Django 5.0.12 on 2025-07-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_alter_labnotebook_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labnotebook',
            name='file',
        ),
    ]
