# Generated by Django 5.0.12 on 2025-03-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('customers', '0002_customer_init_email_customer_init_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=120, null=True)),
                ('init_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('init_email_confirmed', models.BooleanField(default=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
