# Generated by Django 5.0.13 on 2025-04-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0019_organizationsubscription_delete_usersubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('starter', 'Starter Plan Access'), ('business', 'Business Plan Access'), ('enterprise', 'Enterprise Plan Access')]},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['starter', 'business', 'enterprise'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
