# Generated by Django 5.0.12 on 2025-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_for_labs',
            field=models.BooleanField(default=False, help_text='Show on Labs landing page'),
        ),
    ]
