# Generated by Django 5.0.12 on 2025-06-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0021_subscription_is_for_labs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='permissions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'codename__in': ['starter', 'business', 'enterprise'], 'content_type__app_label': 'subscriptions'}, to='auth.permission'),
        ),
    ]
