"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
from django.contrib.messages import constants as messages
from storages.backends.s3boto3 import S3Boto3Storage
import boto3

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Email config
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", cast=str, default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", cast=str, default="587")  # Recommended
EMAIL_HOST_USER = config("EMAIL_HOST_USER", cast=str, default=None)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", cast=str, default=None)
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", cast=str, default=None)
EMAIL_USE_TLS = config(
    "EMAIL_USE_TLS", cast=bool, default=True
)  # Use EMAIL_PORT 587 for TLS
EMAIL_USE_SSL = config(
    "EMAIL_USE_SSL", cast=bool, default=False
)  # Use MAIL_PORT 465 for SSL


ADMIN_USER_NAME = config("ADMIN_USER_NAME", default="Admin user")
ADMIN_USER_EMAIL = config("ADMIN_USER_EMAIL", default=None)

MANAGERS = []
ADMINS = []
if all([ADMIN_USER_NAME, ADMIN_USER_EMAIL]):
    # 500 errors are emailed to these users
    ADMINS += [(f"{ADMIN_USER_NAME}", f"{ADMIN_USER_EMAIL}")]
    MANAGERS = ADMINS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

BASE_URL = config("BASE_URL", default=None)

SITE_DOMAIN = config("RAILWAY_PUBLIC_DOMAIN", default="")

ALLOWED_HOSTS = [
    ".railway.app",
    "modelmint-production.up.railway.app",
    "modelmint.co",
    SITE_DOMAIN,
]

if DEBUG:
    ALLOWED_HOSTS += ["127.0.0.1", "localhost"]


# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


THIRD_PARTY_APPS = [
    "django_celery_beat",
]

LOCAL_APPS = [
    "accounts.apps.AccountsConfig",
    "landing.apps.LandingConfig",
    "subscriptions.apps.SubscriptionsConfig",
    "customers.apps.CustomersConfig",
    "checkouts.apps.CheckoutsConfig",
    "dashboard.apps.DashboardConfig",
    "analytics.apps.AnalyticsConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # custom context processors
                "accounts.context_processors.organization_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

CONN_MAX_AGE = config("CONN_MAX_AGE", cast=int, default=30)
DATABASE_URL = config("DB_URL", default=None)

if DATABASE_URL is not None:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=CONN_MAX_AGE,
            conn_health_checks=True,
        )
    }

# Replace the DATABASES section of your settings.py with this
# DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.postgresql',
#     'NAME': config('PGDATABASE'),
#     'USER': config('PGUSER'),
#     'PASSWORD': config('PGPASSWORD'),
#     'HOST': config('PGHOST'),
#     'PORT': config('PGPORT', 5432),
#     'OPTIONS': {
#       'sslmode': 'require',
#     },
#   }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# ✅ Use S3 for media, WhiteNoise for static files
USE_S3 = config("USE_S3", default=False, cast=bool)

STORAGES = {
    # 🔹 Use S3 for media files
    "default": (
        {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        }
        if USE_S3
        else {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {"location": os.path.join(BASE_DIR, "media")},
        }
    ),
    # 🔹 Use WhiteNoise for static files
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ✅ AWS S3 Configurations (For Media Files)
if USE_S3:
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-west-2")
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

    # 🔒 Secure Media Files (Not Publicly Accessible by Default)
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }

# ✅ Static & Media URLs
STATIC_URL = "/static/"  # Served via WhiteNoise
MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/" if USE_S3 else "/media/"

# ✅ Static & Media Paths
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_ROOT = (
    os.path.join(BASE_DIR, "media") if not USE_S3 else None
)  # Only for local dev

# ✅ Enable WhiteNoise Compression & Caching
WHITENOISE_KEEP_ONLY_HASHED_FILES = True


# ✅ Custom Storage for Public Profile Pictures & Private Uploads
class PublicMediaStorage(S3Boto3Storage):
    """Storage class for publicly accessible profile pictures."""

    location = "profile_pictures"
    default_acl = "public-read"
    file_overwrite = False


class PrivateMediaStorage(S3Boto3Storage):
    location = "uploads"
    default_acl = "private"
    custom_domain = False
    querystring_auth = True
    querystring_expire = 3600

    def get_presigned_url(self, file_path, expires_in=3600):
        if not USE_S3:
            return f"/media/{file_path}"  # fallback for local dev
        import boto3  # ← safely imported here, avoids global dependency

        s3_client = boto3.client(
            "s3",
            aws_access_key_id=AWS_ACCESS_KEY_ID,
            aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
            region_name=AWS_S3_REGION_NAME,
        )
        return s3_client.generate_presigned_url(
            "get_object",
            Params={"Bucket": AWS_STORAGE_BUCKET_NAME, "Key": file_path},
            ExpiresIn=expires_in,
        )


# ✅ Allowlist Trusted Domains (Including Railway & ModelMint)
CSRF_TRUSTED_ORIGINS = [
    "https://modelmint.co",
    "https://www.modelmint.co",
    "https://modelmint-production.up.railway.app",  # ✅ Railway App Domain
    f"https://{config('SITE_DOMAIN', default='modelmint.co')}",
]

# ✅ Redis Broker URL (Railway or Local)
REDIS_URL = config("REDIS_URL", default="redis://localhost:6379/1")

# ✅ Celery configurations
CELERY_BROKER_URL = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = REDIS_URL

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ✅ Custom User Model
AUTH_USER_MODEL = "accounts.User"

# ✅ Custom Message Tags for Bootstrap Alerts
MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

MAX_UPLOAD_SIZE_BYTES = 1181116006

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} — {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
