# Generated by Django 5.0.12 on 2025-04-25 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_userprofile_name'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metrics', models.ManyToManyField(related_name='selected_for_dashboard', to='analytics.metric')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_selection', to='accounts.organization')),
            ],
        ),
    ]
