# Generated by Django 5.0.12 on 2025-06-23 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_alter_report_upload'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetricOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardselection')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.metric')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('dashboard', 'metric')},
            },
        ),
    ]
