# Generated by Django 5.0.12 on 2025-03-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
    ]
