# Generated by Django 5.0.12 on 2025-06-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('client', 'Client (DaaS)'), ('lab', 'Labs (Data Scientists)')], default='client', help_text='Indicates whether this org is a client (DaaS) or Labs (data scientists)', max_length=20),
        ),
    ]
