# Generated by Django 5.0.12 on 2025-07-16 01:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo for dashboards, emails, and reports', null=True, upload_to='org_logos/')),
                ('primary_color', models.CharField(default='#198754', help_text='Primary branding color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #123ABC).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary branding color', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #123ABC).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('text_color', models.CharField(default='#000000', help_text='Text color used in dashboards or reports', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #123ABC).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color for dashboards/reports', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #123ABC).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('tagline', models.CharField(blank=True, help_text='Short slogan or description of the organization', max_length=255, null=True)),
                ('website', models.URLField(blank=True, help_text='Public website or landing page', null=True)),
                ('industry', models.CharField(blank=True, choices=[('tech', 'Technology'), ('data_science', 'Data Science'), ('ai', 'AI'), ('finance', 'Finance & Banking'), ('health', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail & E-commerce'), ('media', 'Media & Entertainment'), ('consulting', 'Consulting & Services'), ('manufacturing', 'Manufacturing'), ('real_estate', 'Real Estate'), ('non_profit', 'Non-Profit'), ('government', 'Government'), ('energy', 'Energy & Utilities'), ('transportation', 'Transportation & Logistics'), ('other', 'Other')], help_text='Industry sector of the organization', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.organization')),
            ],
        ),
    ]
