# Generated by Django 5.0.12 on 2025-07-16 01:58

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organizationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo for dashboards, emails, and reports', null=True, storage=config.storages.OrgLogoStorage(), upload_to=''),
        ),
    ]
