# Generated by Django 5.0.12 on 2025-02-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataupload',
            name='processing_notes',
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='job_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
