# Generated by Django 5.0.12 on 2025-05-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='drive_link',
            field=models.URLField(blank=True, help_text='If provided, the team will download the data from this link.', null=True),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.CharField(blank=True, help_text='S3 key for the uploaded file', max_length=1024, null=True),
        ),
    ]
