# Generated by Django 5.0.12 on 2025-05-06 02:31

import analytics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dataupload_drive_link_alter_dataupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=analytics.utils.upload_to_metric),
        ),
    ]
