# Generated by Django 5.0.12 on 2025-03-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dataupload_processing_notes_alter_dataupload_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('table', 'Table'), ('plot', 'Plot'), ('single_value', 'Single Value'), ('text', 'Text')], max_length=20)),
                ('name', models.CharField(help_text='Name of the metric', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='metrics/')),
                ('value', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order of metric')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.dataupload')),
            ],
            options={
                'ordering': ['datasource__organization', 'datasource', '-created_at'],
                'unique_together': {('datasource', 'position')},
            },
        ),
    ]
