# Generated by Django 5.0.12 on 2025-05-09 23:49

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_metric_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='job_instructions',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed instructions on what needs to be done with the data.', verbose_name='Instructions'),
        ),
    ]
