# Generated by Django 5.0.12 on 2025-03-03 20:56

import analytics.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=analytics.utils.upload_to_metric),
        ),
    ]
