# Generated by Django 5.0.12 on 2025-05-10 20:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_dataupload_job_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='value',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
