# Generated by Django 5.0.12 on 2025-05-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_metric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
