# Generated by Django 5.0.12 on 2025-03-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_metric_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(help_text='Column names of the table')),
                ('data', models.JSONField(help_text='Row data stored as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_data', to='analytics.metric')),
            ],
        ),
    ]
