# Generated by Django 5.0.13 on 2025-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_tablemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', help_text='Track the background upload status', max_length=20),
        ),
    ]
