# Generated by Django 5.0.13 on 2025-03-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_dataupload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.CharField(help_text='S3 key for the uploaded file', max_length=1024),
        ),
    ]
