# Generated by Django 5.0.12 on 2025-06-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_jupyterreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='is_preview',
            field=models.BooleanField(default=True, help_text='True if the metric is in preview mode and not yet visible to the user.'),
        ),
    ]
