# Generated by Django 5.0.12 on 2025-04-22 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_name'),
        ('analytics', '0008_alter_dataupload_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupload',
            options={'ordering': ['-created_at', 'organization', 'dataset', '-version']},
        ),
        migrations.AddField(
            model_name='dataupload',
            name='operation',
            field=models.CharField(choices=[('create', 'Create New Dataset'), ('append', 'Append to Existing Dataset'), ('replace', 'Replace Dataset')], default='create', help_text='Create, append, or replace the dataset.', max_length=10),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version of this upload within the dataset.'),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the dataset (e.g. 'Monthly Sales')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the dataset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_datasets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='dataupload',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='Group uploads by versioned datasets.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='analytics.dataset'),
        ),
    ]
