# Generated by Django 5.0.12 on 2025-06-20 17:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_migrate_metrics_to_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataupload',
            name='job_instructions',
        ),
        migrations.RemoveField(
            model_name='dataupload',
            name='processing_notes',
        ),
        migrations.RemoveField(
            model_name='dataupload',
            name='used_for_processing',
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='analytics.dataset'),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='drive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='file',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='operation',
            field=models.CharField(choices=[('create', 'Create New Dataset'), ('append', 'Append to Existing'), ('replace', 'Replace Dataset')], default='create', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='report',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.dataupload'),
        ),
    ]
