# Generated by Django 5.0.12 on 2025-06-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_remove_dataupload_job_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jupyterreport',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jupyter_reports', to='analytics.report'),
        ),
    ]
