# Generated by Django 5.0.12 on 2025-06-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_jupyterreport_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.dataupload'),
        ),
    ]
