# Generated by Django 5.0.12 on 2025-07-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_alter_report_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/examples/'),
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('static', 'Static Report'), ('dynamic', 'Dynamic Dashboard')], default='static', max_length=20),
        ),
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('plot', 'Plot'), ('single_value', 'Single Value'), ('text', 'Text')], max_length=30),
        ),
        migrations.CreateModel(
            name='DynamicDashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(help_text='Auto-generated dashboard config.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to='analytics.metric')),
            ],
        ),
    ]
