# Generated by Django 5.0.12 on 2025-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_report_example_file_report_type_alter_metric_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='type',
            field=models.CharField(choices=[('table', 'Table'), ('plot', 'Plot'), ('single_value', 'Single Value'), ('text', 'Text'), ('dynamic_csv_dashboard', 'Dynamic CSV Dashboard')], max_length=30),
        ),
    ]
