# Generated by Django 5.0.12 on 2025-07-02 18:36

import analytics.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_alter_metric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to=analytics.utils.utils.upload_to_example_file),
        ),
    ]
