# Generated by Django 5.0.12 on 2025-07-02 19:29

import analytics.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_alter_report_example_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to=analytics.utils.utils.upload_to_example_file, validators=[analytics.utils.utils.validate_file_extension]),
        ),
    ]
