name: 4 - Branch Neon DB for Django Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DEBUG: 0
      NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
      NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
      NEON_PROD_BRANCH: "production" # Cambiado de "main" a "production"
      NEON_GITHUB_BRANCH: "gh-test" # Puedes cambiar este nombre si lo prefieres
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      AWS_S3_REGION_NAME: ${{ secrets.AWS_S3_REGION_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"

      - name: Install Neon CLI
        run: npm install -g neonctl

      - name: Delete previous temp branch if it exists
        continue-on-error: true
        run: |
          echo "🧹 Deleting previous branch ${{ env.NEON_GITHUB_BRANCH }} if exists..."
          neonctl branches delete "${{ env.NEON_GITHUB_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}" || true

      - name: Create new GitHub Actions branch from production
        run: |
          neonctl branches create --name "${{ env.NEON_GITHUB_BRANCH }}" --parent "${{ env.NEON_PROD_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}"

      - name: Set DATABASE_URL from new Neon branch
        run: |
          NEW_DB_URL=$(neonctl connection-string --branch "${{ env.NEON_GITHUB_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}")
          echo "DATABASE_URL=$NEW_DB_URL" >> $GITHUB_ENV

      - name: Generate Django Secret Key
        run: |
          echo "DJANGO_SECRET_KEY=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Migrations
        working-directory: ./src
        run: python manage.py migrate

      - name: Run Django Tests
        working-directory: ./src
        run: python manage.py test

      - name: Clean up Neon branch
        if: always()
        continue-on-error: true
        run: |
          echo "🧹 Deleting temp Neon branch ${{ env.NEON_GITHUB_BRANCH }}..."
          neonctl branches delete "${{ env.NEON_GITHUB_BRANCH }}" --project-id "${{ env.NEON_PROJECT_ID }}"
